school/school/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('schoolapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

school/schoolapp/urls.py
from django.urls import path
from . import views
app_name = 'schoolapp'
urlpatterns = [
    path('', views.home , name='home'),
    path('login/', views.login , name='login'),
    path('logout/', views.logout , name='logout'),
    path('register/', views.Register , name='register'),
    path('new/', views.new , name='new'),
    path('n/', views.n , name='n'),

]

school/schoolapp/models.py
from django.db import models

# Create your models here.
class Datas(models.Model):
    name = models.CharField(max_length=250)
    dob = models.DateField()
    age = models.IntegerField()
    gender = models.CharField(max_length=100)
    phone = models.IntegerField()
    email = models.CharField(max_length=250)
    department = models.CharField(max_length=250)
    course = models.CharField(max_length=250)
    purpose = models.CharField(max_length=250)
    materials = models.CharField(max_length=1000)



school/schoolapp/views.py
from django.shortcuts import render,redirect
from django.contrib import messages,auth
from django.contrib.auth.models import User
from .models import Datas

# Create your views here.
def home(req):
    return render(req, 'index.html')
def login(req):
    if req.method == 'POST':
        username = req.POST['username'] 
        password = req.POST['password'] 
        print(username)
        user = auth.authenticate(username=username,password= password)

        if user is not None:
            auth.login(req,user)
            return render(req, 'new.html')
        else:
            messages.info(req,"invalid Credentials")
    return render(req, 'login.html')

def logout(req):
    auth.logout(req)
    return render(req, 'index.html')
def Register(req):
    if req.method == 'POST':
        username = req.POST['username'] 
        password = req.POST['password'] 
        cpassword = req.POST['cpassword']
        if password == cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(req,"Username already taken")
                return render(req, 'register.html')
            else:
                user = User.objects.create_user(username = username,password=password)
                user.save()
                print("saved")
                
                return render(req, 'login.html')
        else:
            messages.info(req,"password not matching")
    
        
    return render(req, 'register.html')
    
def new(req):
    if req.method == 'POST':
        name = req.POST['name']
        dob = req.POST['dob']
        age = req.POST['age']
        gender = req.POST['gender']
        phone = req.POST['phone']
        mail = req.POST['mail']
        department = req.POST['department']
        course = req.POST['course']
        purpose = req.POST['purpose']
        materials =[]
        if 'material1' in req.POST:
            materials.append('Note Book')
        if 'material2' in req.POST:
            materials.append('Pen')
        if 'material3' in req.POST:
            materials.append('Exam Papers')
        
        data = Datas.objects.create(name=name,dob=dob,age=age,gender=gender,phone=phone,email=mail,department=department,course=course,purpose=purpose,materials=materials)
        data.save()
        print("saved")
        messages.info(req,"Order Confirmed")
        return render(req, 'new.html')
    else:
        messages.info(req,"invalid Credentials")
        return render(req, 'new.html')
    return render(req, 'new.html')

def n(req):
    return render(req,"ind.html")

school/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- Google online fonts -->
    <link href="//fonts.googleapis.com/css?family=Work+Sans:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800&display=swap" rel="stylesheet">
    <!-- Template CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
<link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/about.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/about_responsive.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"  >
    <style>
      .dropbtn {
    font-size: 16px;
    border: none;
  }
  
  .dropdown {
    position: relative;
    display: inline-block;
  }
  
  .dropdown-content {
    display: none;
    position: absolute;
    background-color: #f1f1f1;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
  }
  
  .dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
  }
  
  .dropdown-content a:hover {background-color: #ddd;}
  
  .dropdown:hover .dropdown-content {display: block;}
  
  
    </style>
    <script>
      // Define course options for each department
      var courseOptions = {
          'Commerce': ['BBA', 'BCom', 'MCom'],
          'Science': ['BSc', 'MSc', 'PhD'],
          'Arts': ['BA', 'MA', 'Drama'],
          
      };

      
      function updateCourses() {
          var departmentDropdown = document.getElementById('department');
          var courseDropdown = document.getElementById('course');
          var selectedDepartment = departmentDropdown.value;
          var courses = courseOptions[selectedDepartment];

          
          courseDropdown.innerHTML = '';

          // Add new course options
          for (var i = 0; i < courses.length; i++) {
              var option = document.createElement('option');
              option.value = courses[i];
              option.text = courses[i];
              courseDropdown.appendChild(option);
          }
      }
  </script>
</head>
<body>
   
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <img src="{% static 'images/2.jpg' %}" width="30px" alt="">
          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'schoolapp:home' %}">Home</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'schoolapp:logout' %}">logout</a>
              </li>

              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'schoolapp:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'schoolapp:register' %}">Register</a>
              </li>
              {% endif %}
              
               
              <div class=" nav-item dropdown">
                <button class="nav-link dropbtn">Department</button>
                <div class="dropdown-content">
                  <a href="#">Commerce</a>
                  <a href="#">Science</a>
                  <a href="#">Arts</a>
                </div>
              </div>
              
            </ul>
          </div>
        </div>
      </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

school/templates/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block body %}

{% load static %}



<div class="container">
    <div class="row">
        <div class="col text-center">
            
            <div class="section_title"><h2>A few words about us</h2></div>
        </div>
    </div>
    <div class="row about_row">
        <div class="col-lg-6">
            <div class="about_content">
                <div class="text_highlight">Welcome to our comprehensive college website that offers a diverse range of academic programs to cater to your educational aspirations. </div>
                <div class="about_text">
                    <p> For those inclined towards the dynamic world of commerce, we provide an array of courses including 'BBA' (Bachelor of Business Administration) to foster effective management skills, 'BCom' (Bachelor of Commerce) to lay a strong foundation in business principles, and 'MCom' (Master of Commerce) for an advanced understanding of economic dynamics. If the realm of science captivates you, we offer 'BSc' (Bachelor of Science) programs for in-depth scientific exploration, 'MSc' (Master of Science) programs for specialized knowledge, and 'PhD' courses for those /seeking to contribute to the frontiers of scientific discovery.<p>
                </div>
                <div class="button about_button"><a href="{% url 'schoolapp:login' %}">Login</a></div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="about_image"><img src="{% static 'images/about_2.jpg' %}" alt=""></div>
        </div>
    </div>
</div>
</div><br><br>



<!-- Why Choose Us -->

<div class="why">
<div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="{% static 'images/college_3.jpg' %} " data-speed="0.8"></div>
<div class="container">
    <div class="row">
        <div class="col text-center">
            <div class="section_title"><h2 style="color: black;">Why choose us?</h2></div><br>
        </div>
    </div>
    <div class="row why_row">
        
        <!-- Why item -->
        
        <div class="col-lg-4 why_col">
            <div class="why_item">
                <div class="why_image">
                    <img src="{% static 'images/students.jpg' %}" alt="">
                    <div class="why_icon d-flex flex-column align-items-center justify-content-center">
                        <img src="{% static 'images/book.svg' %}" alt="">
                    </div>
                </div>
                <div class="why_content text-center">
                    <div class="why_title">Academic</div>
                    <div class="why_text">
                        <p>
                            Our institution is committed to delivering education of the highest quality, ensuring that our teaching provides nothing but the best to our students.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 why_col">
            <div class="why_item">
                <div class="why_image">
                    <img src="{% static 'images/graduation.jpg' %}" alt="">
                    <div class="why_icon d-flex flex-column align-items-center justify-content-center">
                        <img src="{% static 'images/book.svg' %}" alt="">
                    </div>
                </div>
                <div class="why_content text-center">
                    <div class="why_title">Achievement</div>
                    <div class="why_text">
                        
                        <p>We take pride in maintaining a consistently high pass percentage, reflecting our dedication to academic excellence and student success.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 why_col">
            <div class="why_item">
                <div class="why_image">
                    <img src="{% static 'images/lib.jpg' %}" alt="">
                    <div class="why_icon d-flex flex-column align-items-center justify-content-center">
                        <img src="{% static 'images/book.svg' %}" alt="">
                    </div>
                </div>
                <div class="why_content text-center">
                    <div class="why_title">Knowledge</div>
                    <div class="why_text">
                        <p>
                            Our well-stocked library ensures that students have access to a wide range of books, fostering a conducive environment for acquiring extensive knowledge.</p>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</div>
</div>




<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'styles/bootstrap4/popper.js' %}"></script>
<script src="{% static 'styles/bootstrap4/bootstrap.min.js' %}"></script>
<script src="{% static 'plugins/greensock/TweenMax.min.js' %}"></script>
<script src="{% static 'plugins/greensock/TimelineMax.min.js' %}"></script>
<script src="{% static 'plugins/scrollmagic/ScrollMagic.min.js' %}"></script>
<script src="{% static 'plugins/greensock/animation.gsap.min.js' %}"></script>
<script src="{% static 'plugins/greensock/ScrollToPlugin.min.js' %}"></script>
<script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
<script src="{% static 'plugins/easing/easing.js' %}"></script>
<script src="{% static 'plugins/parallax-js-master/parallax.min.js' %}"></script>
<script src="{% static 'js/about.js' %}"></script>



{% endblock %}

school/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block body %}
<div class="container">

  <div class="login-box">
    
    <form action="" method="post" style="padding-top: 13vh; padding-left: 28vw;">
      {% csrf_token %}
      
      <div class="rounded col-sm-6" style="border: 2px solid black;">
        <div class="inside" style="padding: 0.5rem;">
        <h1 style="color: #0d6efd; text-align: center;"><strong>LOGIN</strong></h1><br>
        <!-- Username input -->
        <div class="form-outline mb-4">
          <label class="form-label" for="form2Example1" style="text-align: left;">Username</label>
          <input type="text" name="username" id="form2Example1" class="form-control" required/>
        </div>

        <!-- Password input -->
        <div class="form-outline mb-4">
          <label class="form-label" for="form2Example2">Password</label>
          <input type="password" name="password" id="form2Example2" class="form-control" required/>
        </div>

        
        <div class="text-center">
          <!-- Submit button -->
          <button type="submit" style="text-align: center;" class="btn btn-primary btn-block mb-4">Sign in</button>

          <!-- Register buttons -->
          
          <p>Not a member? <a href="{% url 'schoolapp:register' %}">Register</a></p>
        </div>
        
        {% for msg in messages %}
          <p style="color: crimson;"><b>{{msg}}</b></p>
        {% endfor %}
      </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

school/templates/new.html
{% extends 'base.html' %}
{% block title %}New{% endblock %}
{% block body %}

<div class="container">
    <form action="" method="post" style="padding-top: 0.8rem; padding-left: 10vw; padding-right: 10vw;">
        {% csrf_token %}
        <div class="rounded col-sm-12" style="border: 2px solid black;">
            <div class="inside row" style="padding: 0.5rem;">
                <h1 style="color: #0d6efd; text-align: center;"><strong>DETAILS</strong></h1><br>
                <div class="form-outline mb-4 col-md-6">
                    <label for="name" class="form-label" style="text-align: left;"><b>Name</b></label>
                    <input type="text" name="name" id="name" class="form-control" required>
                </div>
                <div class="form-outline mb-4 col-md-6">
                    <label for="dob" class="form-label" style="text-align: left;"><b>Date Of Birth</b></label>
                    <input type="date" name="dob" id="dob" class="form-control" required>
                </div>
                <div class="form-outline mb-4 col-md-6">
                    <label for="age" class="form-label" style="text-align: left;"><b>Age</b></label>
                    <input type="number" name="age" id="age" class="form-control" required>
                </div>
                <div class="form-outline mb-4 col-md-6">
                    <label for="gender" class="form-label" style="text-align: left;"><b>Gender</b></label>
                    <select name="gender"  id="gender" class="form-control" >
                        <option value="male">Male</option>
                        <option value="female">Female</option>
                    </select>
                </div>
                <div class="form-outline mb-4 col-md-6">
                    <label for="phone" class="form-label" style="text-align: left;"><b>Phone Number</b></label>
                    <input type="number" name="phone" id="phone" class="form-control" required>
                </div>
                <div class="form-outline mb-4 col-md-6">
                    <label for="mail" class="form-label" style="text-align: left;"><b>Email</b></label>
                    <input type="email" name="mail" id="mail" class="form-control" required>
                </div>
                <div class="form-outline mb-4 col-md-6">
                    <label for="department" class="form-label" style="text-align: left;"><b>Department</b></label>
                    <select id="department" name="department" class="form-control" onchange="updateCourses()">
                        <option value="Commerce">Commerce</option>
                        <option value="Science">Science</option>
                        <option value="Arts">Arts</option>
                        
                    </select>
                </div>
                <div class="form-outline mb-4 col-md-6">
                    <label for="course" class="form-label" style="text-align: left;"><b>Courses</b></label>
                    <select id="course" name="course" class="form-control">
                        <option value="BBA">BBA</option>
                        <option value="BCom">BCom</option>
                        <option value="MCom">MCom</option>
                    </select>
                </div>
                <div class="form-outline mb-4 col-md-6">
                    <label for="purpose" class="form-label" style="text-align: left;"><b>Purpose</b></label>
                    <select id="purpose" name="purpose" class="form-control">
                        <option value="Enquiry">Enquiry</option>
                        <option value="Place Order">Place Order</option>
                        <option value="Return">Return</option>
                        
                    </select>
                </div>
                <div class="form-outline mb-4 col-md-6">
                    <label for="name" class="form-label" style="text-align: left;"><b>Materials Provided:</b></label><br>
                    <input type="checkbox" id="notebook" name="material1" value="Note Book">
                    <label for="notebook">Note Book</label>
                    <input type="checkbox" id="pen" name="material2" value="Pen">
                    <label for="pen">Pen</label>
                    <input type="checkbox" id="papers" name="material3" value="Exam Papers">
                    <label for="papers">Exam Papers</label>
                </div>
                <div class="text-center">
                    <!-- Submit button -->
                    <button type="submit" style="text-align: center;" class="btn btn-success btn-block mb-4">Submit</button>
                    {% for msg in messages %}
                    <p>{{msg}} <a href="{% url 'schoolapp:home' %}">Home</a></p>
                    {% endfor %}
                </div>  
            </div>
        </div>  
    </form>
</div>
{% endblock %}

school/templates/register.html
{% extends 'base.html' %}
{% block title %}Register{% endblock %}
{% block body %}

<div class="container">
  
  <form action="" method="post" style="padding-top: 4vh; padding-left: 28vw;">
    {% csrf_token %}
    <div class="rounded col-sm-6" style="border: 2px solid black;">
      <div class="inside" style="padding: 0.5rem;">
      <h1 style="color: #0d6efd; text-align: center;"><strong>REGISTER</strong></h1><br>
      <!-- Username input -->
      <div class="form-outline mb-4">
        <label class="form-label" for="form2Example1">Username</label>
        <input type="text" name="username" id="form2Example1" class="form-control" required/>
      </div>
    
      <!-- Password input -->
      <div class="form-outline mb-4">
        <label class="form-label" for="form2Example2">Password</label>
        <input type="password" name="password" id="form2Example2" class="form-control" required/>
      </div>

      <!-- Confirm Password input -->
      <div class="form-outline mb-4">
        <label class="form-label" for="form2Example3">Confirm Password</label>
        <input type="password" name="cpassword" id="form2Example3" class="form-control" required/>
      </div>
    
      
      <div class="text-center">
        <!-- Submit button -->
        <input type="submit" class="btn btn-primary btn-block mb-4" value="Sign up">
        <!-- Register buttons -->
        <p>Already a member? <a href="{% url 'schoolapp:login' %}">Login</a></p>
      </div>
      {% for msg in messages %}
        <p style="color: crimson;"><b>{{msg}}</b></p>
      {% endfor %}
      </div>
    </div>
  </form>
</div>
{% endblock %}